language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "iojs"
notifications:
  slack: leolouis:3ABtsED6Nrz7Vfb6eD2EXBbY
install: npm install
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: "Encrypted API key"
    
